### ISSUE TITLE
Question: Reasoning and Inference included?

### ISSUE THREAD

**Issue by Dletta** [alexge233/cgpp#1]
Hi @alexge233,

Is an inference engine and/or reasoning mechanism built into your library, or is this just a knowledge representation implementation?

**Comment by alexge233** [comment]
Hi @Dletta no there is no inference or logic, but I presume it should be straightforward to implement should you choose to, via graph manipulators. Currently as it stands it is simply KR, and I did intend to template it.

**Comment by Dletta** [comment]
@alexge233 thanks, I will star to get some hints. Not sure I am at the point yet, where I could implement reasoning, I just know the formalism, not how to implement them. Any good resources appreciated.
